/' http://plantuml.com/class-diagram '/ 
@startuml CG-N2_2

title Diagrama de Classes
footer Computação Gráfica

!include ../../gcg-cg/CG_Biblioteca/docs/umlClasses.wsd

Program : Mundo window
Program : {static} void Main(string[] args)
Program o-down- Mundo

Mundo : + {static} Mundo instance
Mundo : + Mundo(int width, int height)
Mundo : + static Mundo getInstance()
Mundo : - Camera camera
Mundo : # List<Objeto> objetosLista
Mundo : # override void OnLoad(EventArgs e)
Mundo : # override void OnUpdateFrame(FrameEventArgs e)
Mundo : # override void OnRenderFrame(FrameEventArgs e)
Mundo : # override void OnKeyDown(OpenTK.Input.KeyboardKeyEventArgs e)
Mundo : # override void OnMouseMove(MouseMoveEventArgs e)
Mundo : - void Sru3D()
Mundo o-down- Objeto
Camera <-left- Mundo

Objeto : # string rotulo
Objeto : - PrimitiveType primitivaTipo
Objeto : - float primitivaTamanho
Objeto : - BBox bBox
Objeto : - List<Objeto> objetosLista
Objeto : + Objeto(string rotulo)
Objeto : # PrimitiveType PrimitivaTipo { get; set }
Objeto : # float PrimitivaTamanho { get ; set }
Objeto : + void Desenhar()
Objeto : # abstract void DesenharAramado()
Objeto : + void FilhoAdicionar(Objeto filho)
Objeto : + void FilhoRemover(Objeto filho)
Objeto : # abstract void PontosExibir()
Objeto : + void PontosExibirObjeto()
Objeto <|-down- ObjetoAramado
BBox <-left- Objeto

ObjetoAramado : # List<Ponto4D> pontosLista
ObjetoAramado : + ObjetoAramado(string rotulo)
ObjetoAramado : # override void DesenharAramado()
ObjetoAramado : # void PontosAdicionar(Ponto4D pto)
ObjetoAramado : # void PontosRemoverTodos()
ObjetoAramado : # override void PontosExibir()
ObjetoAramado o-down- Ponto4D
ObjetoAramado <|-down- Retangulo

Retangulo : - Ponto4D ptoInfEsq
Retangulo : - Ponto4D ptoSupDir
Retangulo : + Retangulo(string rotulo,Ponto4D ptoInfEsq, Ponto4D ptoSupDir)
Retangulo : - void GerarPtosRetangulo()
Retangulo : + void MoverPtoSupDir(Ponto4D ptoMover)

@enduml
